# Generated by Django 6.1.1 on 2026-09-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_storeproductoverride_override_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='payment_terms',
            field=models.CharField(default='ระยะเวลา 30 วัน', max_length=200),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=5),
        ),
    ]
