# Generated by Django 6.1.1 on 2026-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_deliverynote_grand_total_deliverynote_payment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynoteitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
