# Generated by Django 6.1.1 on 2026-09-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_deliverynoteitem_amount_deliverynoteitem_unit_price'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='ingestion.purchaseorderbatch'),
        ),
    ]
