# Generated by Django 6.1.1 on 2026-09-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_deliverynote_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='customer_head_office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='customer_tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='po_numbers',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
