# Generated by Django 6.1.1 on 2026-09-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_invoice_invoicelineitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='external_invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
