# Generated by Django 6.1.1 on 2026-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_invoicelineitem_external_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
