# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_deliverynote_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(
                choices=[
                    ('BILLING_STATEMENT', 'ใบวางบิล'),
                    ('DETAILED_INVOICE', 'Invoice')
                ],
                default='BILLING_STATEMENT',
                max_length=20
            ),
        ),
    ]
