#!/bin/bash

# Generate WSGI Configuration File
# This creates a WSGI config that you can copy to PythonAnywhere

echo "========================================="
echo "WSGI Configuration Generator"
echo "========================================="
echo ""

# Get username
read -p "Enter your PythonAnywhere username: " USERNAME

if [ -z "$USERNAME" ]; then
    echo "❌ Username is required!"
    exit 1
fi

PROJECT_DIR="$HOME/oem-orders"
VENV_DIR="$PROJECT_DIR/venv"
WSGI_FILE="${USERNAME}_pythonanywhere_com_wsgi.py"

echo ""
echo "Generating WSGI configuration..."
echo ""

cat > "$WSGI_FILE" << EOF
# +++++++++++ DJANGO +++++++++++
# Django settings module
# Generated by create_wsgi_config.sh

import os
import sys

# Add your project directory to the sys.path
project_home = '/home/${USERNAME}/oem-orders'
if project_home not in sys.path:
    sys.path.insert(0, project_home)

# Set environment variable to point to Django settings module
os.environ['DJANGO_SETTINGS_MODULE'] = 'config.settings'

# Activate virtual environment
activate_this = '/home/${USERNAME}/oem-orders/venv/bin/activate_this.py'
try:
    with open(activate_this) as f:
        exec(f.read(), {'__file__': activate_this})
except FileNotFoundError:
    # If activate_this.py doesn't exist, add venv to path manually
    venv_path = '/home/${USERNAME}/oem-orders/venv/lib/python3.10/site-packages'
    if venv_path not in sys.path:
        sys.path.insert(0, venv_path)

# Import Django WSGI application
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
EOF

echo "✅ WSGI configuration file created: $WSGI_FILE"
echo ""
echo "========================================="
echo "Installation Instructions:"
echo "========================================="
echo ""
echo "1. Copy the content of this file:"
echo "   cat $WSGI_FILE"
echo ""
echo "2. On PythonAnywhere, go to Web tab"
echo ""
echo "3. Click on 'WSGI configuration file' link"
echo "   (e.g., /var/www/${USERNAME}_pythonanywhere_com_wsgi.py)"
echo ""
echo "4. Delete all content and paste the generated config"
echo ""
echo "5. Save the file"
echo ""
echo "6. Click 'Reload' button in Web tab"
echo ""
echo "Static Files Configuration (in Web tab):"
echo "  URL: /static/"
echo "  Directory: /home/${USERNAME}/oem-orders/staticfiles/"
echo ""
echo "Media Files Configuration (optional):"
echo "  URL: /media/"
echo "  Directory: /home/${USERNAME}/oem-orders/media/"
echo ""

# Display the content
echo "========================================="
echo "WSGI Configuration Content:"
echo "========================================="
cat "$WSGI_FILE"
echo ""
