# Generated by Django 6.1.1 on 2026-09-06 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('parser_key', models.CharField(help_text="Key registered in apps.parsers.registry, e.g. 'donki_v1'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('uom', models.CharField(default='PCS', max_length=20)),
                ('min_order_qty', models.PositiveIntegerField(default=0, help_text='Minimum order quantity per batch; 0 = no minimum')),
                ('sort_rank', models.PositiveIntegerField(blank=True, help_text='Display order in dashboards; blank sorts last', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('sort_rank'), nulls_last=True), 'barcode'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_sku', models.CharField(blank=True, max_length=100)),
                ('min_order_qty_override', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_rank_override', models.PositiveIntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_overrides', to='core.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_overrides', to='core.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'product'), name='unique_product_per_customer')],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='core.customer')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'store_code'), name='unique_store_code_per_customer')],
            },
        ),
    ]
