# Generated by Django 6.1.1 on 2026-09-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('contact_info', models.TextField(blank=True, help_text='Contact details, address, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Factories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='Factory that manufactures this product', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.factory'),
        ),
    ]
