# Generated by Django 6.1.1 on 2026-09-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_factory_product_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.CharField(blank=True, default='', help_text="Product group for factory grouping (e.g., 'Nama Pudding', 'Cake')", max_length=100),
        ),
    ]
