# Generated by Django 6.1.1 on 2026-09-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True, help_text='Full delivery address'),
        ),
    ]
