# Generated by Django 6.1.1 on 2026-09-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_store_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(default='บริษัท ไมด้า อินเตอร์เทรด จำกัด', max_length=200)),
                ('name_en', models.CharField(default='MIDA INTERTRADE CO., LTD.', max_length=200)),
                ('address', models.TextField(default='25 ซอยสุขุมวิท 13 แขวงคลองเตยเหนือ เขตวัฒนา กรุงเทพมหานคร 10110')),
                ('phone', models.CharField(default='02-651-1234', max_length=50)),
                ('fax', models.CharField(blank=True, default='02-651-1235', max_length=50)),
                ('tax_id', models.CharField(default='0105561071598', max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='company/')),
                ('bank_name', models.CharField(default='กสิกรไทย', max_length=100)),
                ('bank_swift', models.CharField(default='KASITHBK', max_length=50)),
                ('bank_account_no', models.CharField(default='066-3-51404-0', max_length=50)),
                ('bank_account_name', models.CharField(default='บริษัท นิวไลน์ โปรดักชั่น จำกัด', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='head_office_address',
            field=models.TextField(blank=True, help_text='Head office address for delivery notes'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Customer tax ID', max_length=50),
        ),
    ]
