# Generated by Django 6.1.1 on 2026-09-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_companyprofile_customer_head_office_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='barcode_override',
            field=models.CharField(blank=True, help_text="Customer-specific barcode; if blank, uses product's default barcode", max_length=20),
        ),
        migrations.AddConstraint(
            model_name='customerproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode_override__gt', '')), fields=('customer', 'barcode_override'), name='unique_barcode_per_customer'),
        ),
    ]
