# Generated by Django 6.1.1 on 2026-09-06 11:49

import apps.ingestion.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=100)),
                ('store_code_raw', models.CharField(blank=True, max_length=50)),
                ('store_name_raw', models.CharField(blank=True, max_length=200)),
                ('source_filename', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to=apps.ingestion.models.po_pdf_upload_path)),
                ('parse_status', models.CharField(choices=[('OK', 'OK'), ('PARTIAL', 'Partial (row count mismatch)'), ('FAILED', 'Failed')], default='OK', max_length=20)),
                ('expected_row_count', models.PositiveIntegerField(default=0)),
                ('parsed_row_count', models.PositiveIntegerField(default=0)),
                ('parser_used', models.CharField(blank=True, max_length=50)),
                ('raw_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.customer')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_raw', models.CharField(max_length=20)),
                ('description_raw', models.CharField(blank=True, max_length=300)),
                ('uom_raw', models.CharField(blank=True, max_length=20)),
                ('qty', models.IntegerField(default=0)),
                ('qty2', models.IntegerField(default=0)),
                ('unit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_no', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='core.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='ingestion.purchaseorder')),
            ],
            options={
                'ordering': ['purchase_order', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.customer')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='ingestion.purchaseorderbatch'),
        ),
    ]
