# Generated by Django 6.1.1 on 2026-09-18 15:25

import apps.ingestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_purchaseorder_entry_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='entry_mode',
            field=models.CharField(choices=[('PDF', 'PDF Upload'), ('MANUAL', 'Manual Entry')], default='PDF', help_text='How this PO was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.ingestion.models.po_pdf_upload_path),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
