# Generated by Django 6.1.1 on 2026-09-06 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='ingestion.purchaseorder'),
        ),
    ]
